#!/usr/bin/env bash
book_path=${1:-""}

if test -z "$book_path"; then
   echo "Usage: $0 <path-to-book>"
   exit 1
fi

if ! test -f "$book_path"; then
   echo "file doesn't exist at given path"
   exit 1
fi

# transform path to absolute
abs_path=$(readlink -f "$book_path")
chapters_dir=$(dirname "$(readlink -f "$0")")/chapters

# remove existing files
rm -rf "$chapters_dir" && mkdir -p "$chapters_dir" && cd "$chapters_dir" || exit 1

awk '{
   if ($1 == "CHAPTER") {
      # extract the chapter
      chapter=substr($0,9, index($0, ".")-9)
      l=sprintf("%s.txt", chapter)
   }
   if (length(chapter) > 0) {
      print $0 >> l
   }
}' "$abs_path"


# Rename the files to start at 1, and remove blank trailing lines.
for f in *; do
   echo "$(<"$f")" > "$f"
done

echo "Done processing \"$book_path\", \
created $(find . -type f | wc -l) files."
