#!/usr/bin/env bash
book_path=${1:-""}

if test -z "$book_path"; then
   echo "Usage: $0 <path-to-book>"
   exit 1
fi

if ! test -f "$book_path"; then
   echo "file doesn't exist at given path"
   exit 1
fi

# 1. replace all punctuation and spaces with new line
# 2. remove all non alphanumeric characters
# 3. make everything lowercase
# 4. sort
tr -s '[:punct:][:space:]' '\n'< "$book_path" | \
   tr -cd '[:alpha:]\n' | \
   tr '[:upper:]' '[:lower:]' | \
   uniq  | \
   awk '
   {
      words[$0]
      sum += length($0);
   } END {
      average_word_length = sum/NR
      words_longer_than_average = 0

      for (word in words)
         if (length(word) >= average_word_length)
            words_longer_than_average++

      printf "There are %d words that are longer \
than the average word length (%0.3f)\n", \
words_longer_than_average, average_word_length
   }'
