#!/usr/bin/env bash
book_path=${1:-""}

# print most frequent word, least frequent word & longest word
function print_stats() {

   title="Statistics for \"$1\""
   underline=$(head -c ${#title} < /dev/zero | tr '\0' '#')
   echo -e "$title\n$underline\n"
   # 1. replace all punctuation and spaces with new line
   # 2. remove all non alphanumeric characters
   # 3. make everything lowercase
   # 4. sort
   tr -s '[:punct:][:space:]' '\n'< "$1" | \
           tr -cd '[:alpha:]\n' | \
           awk '{
                  for (i=1; i<=NF; i++){
                     hist[tolower($i)]++;
                  }
               }
         END {
          min = 1
          for (w in hist) {
             if (length(w) > length(longest))
                longest = w

            times=hist[w]

            if (times >= max) {
               max = times
               maxword = w
            }
            if (times <= min) {
               min = times
               minword = w
            }
         }
         printf "Most frequent word is \"%s\" (appeared %d times)\n", maxword, max
         printf "Least frequent word is \"%s\" (appeared %d times)\n", minword, min
         printf "Longest word is \"%s\" (%d characters)\n",longest, length(longest)
       }'
}

if ! test -z "$book_path"; then
   if ! test -f "$book_path"; then
      echo "file doesn't exist at given path"
      exit 1
   fi
   print_stats "$book_path"
   exit 0
fi

if ! find chapters/* -type f &> /dev/null; then
   echo "chapter files weren't generated."
   exit 1
fi

# iterate all book chapters and print their stats
for chapter in chapters/*; do
   printf "\n%s\n" "$(print_stats "$chapter")"
done
