#!/usr/bin/env bash
book_path=${1:-""}

if test -z "$book_path"; then
   echo "Usage: $0 <path-to-book>"
   exit 1
fi

if ! test -f "$book_path"; then
   echo "file doesn't exist at given path"
   exit 1
fi

# 1. filter allwords next to Alice
# 2. remove 'Alice' from the grep expression
# 3. replace all spaces with a new line
# 4. remove all empty lines
# 5. sort
# 6. get all uniq lines, with the amount they appeared
# 7. sort according to the previous output
# 8. get only the one that has the highest value
result=$(grep -Po '(\w+\s+)?(A|a)lice(\s+\w+)?' "$book_path" | \
        sed 's/Alice//g' | \
        tr '[:space:]' '\n' | \
        sed '/^\s*$/d' | \
        sort | \
        uniq -c | \
        sort -rn | \
        head -n 1)

echo "$result" \
   | awk '{ printf "The most frequent word near \"Alice\" is \"%s\" (appeared %s times)\n", $2, $1 }'
